[build]
  functions = "netlify/functions"  
  publish = "public"                 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/your-function"  # Adjust as necessary for your functions
  status = 200
  force = true
